travis:
  secure:
    BINSTAR_TOKEN: vtHsIWvW116pnw56GkIVXMdD/e33VsgLyQwdWwON9YNKgCHKC8ktBEFKwuRmwpLJXd6U0SwrDZhxvo9FvRIz44GvbrpyyTuxV7bN2cRY3qg2FBpKQZ3SjPsYRoeZkJIb8utdKNNiYb3GOvAJjF81bjAikXGliZEDDVhDdDe+M4eF+0HTIR8n4u1IJbngrJ8MSTWet3ZUDPB+NPS3uhWtTEqLAFeLlTbEyzMYRNvcxCBTmNh2ZHSu+O6HUfhtmefr+Ll1i1pLDUYwjJQ4BLO7T1UFYd2vkgq/YdbmGHMBxuxANves0E+iJPlXrajC3UlHvZhiX5eJIqrwrSaP/X6wiNHesuGnZsAJTNTOiIxOpyuLUVzqB08aXlcuyLXNToxal7fcRHi0b/Mv3g46RDjZiRh4TVElLrhYCrZs93h1dvrFusxWMnCpnlZwDF5G27KCPNhwuTiAfA4/WDp9VIgfguizH8Qtt5In8kDSEMDQpU61u/mVABaBRhZAZgzWmalRT7V7qxkd8LCHgvhmWm+aYZNfR+EB1PIpTVSmG7xYbirtz2WG7kDT7W603ELvG+oPKAFemF7ZvzuxwGOIDujVqbeC0bGzMiB6fpdC9JS1BAhzQGuk/MpxBOfwBj4N7bbnhMXZ5L60PES6F79drLdWi7zBhoX/lUfL19MDOvx0Ib4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
